administrators:
  - "temirov@gmail.com"

environments:
  - description: "Local development"
    origins:
      - "http://localhost:8000"
      - "http://localhost:8080"
      - "http://localhost:8111"
    auth:
      tauthUrl: "http://localhost:8000"
      googleClientId: "991677581607-r0dj8q6irjagipali0jpca7nfp8sfj9r.apps.googleusercontent.com"
      tenantId: "default"
      loginPath: "/auth/google"
      logoutPath: "/auth/logout"
      noncePath: "/auth/nonce"
    authButton:
      text: "signin_with"
      size: "large"
      theme: "outline"
      shape: "circle"

  - description: "Production"
    origins:
      - "https://llm-crossword.mprlab.com"
    auth:
      tauthUrl: "https://tauth.mprlab.com"
      googleClientId: "991677581607-r0dj8q6irjagipali0jpca7nfp8sfj9r.apps.googleusercontent.com"
      tenantId: "default"
      loginPath: "/auth/google"
      logoutPath: "/auth/logout"
      noncePath: "/auth/nonce"
    authButton:
      text: "signin_with"
      size: "large"
      theme: "outline"
      shape: "circle"
