#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

readonly runtime_config_path="js/runtime-auth-config.js"

read_env_file_value() {
  local env_file_path="$1"
  local variable_name="$2"

  if [ ! -f "$env_file_path" ]; then
    return 0
  fi

  sed -n "s/^${variable_name}=//p" "$env_file_path" | head -n 1 | tr -d '\r'
}

resolve_google_client_id() {
  local resolved_google_client_id="${GOOGLE_CLIENT_ID:-}"

  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.tauth" "GOOGLE_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.crosswordapi" "GOOGLE_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.tauth" "APP_GOOGLE_WEB_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  echo "Missing GOOGLE_CLIENT_ID. Set it in the shell, .env.tauth, or .env.crosswordapi." >&2
  return 1
}

resolve_crosswordapi_value() {
  local variable_name="$1"
  local resolved_value="${!variable_name:-}"

  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  resolved_value="$(read_env_file_value ".env.crosswordapi" "$variable_name")"
  printf '%s' "$resolved_value"
}

render_runtime_auth_config() {
  local google_client_id="$1"
  local billing_provider="$2"
  local paddle_environment="$3"
  local paddle_client_token="$4"
  local billing_enabled="false"

  if [ "$billing_provider" = "paddle" ] && [ -n "$paddle_environment" ] && [ -n "$paddle_client_token" ]; then
    billing_enabled="true"
  fi

  cat > "$runtime_config_path" <<EOF
// Generated by scripts/render-runtime-auth-config.sh. Do not edit manually.
(function initRuntimeAuthConfig(globalScope) {
  "use strict";

  globalScope.LLMCrosswordRuntimeConfig = Object.freeze({
    billing: Object.freeze({
      clientToken: "${paddle_client_token}",
      enabled: ${billing_enabled},
      environment: "${paddle_environment}",
      providerCode: "${billing_provider}",
    }),
    googleClientId: "${google_client_id}",
  });
})(window);
EOF
}

main() {
  local google_client_id
  local billing_provider
  local paddle_environment
  local paddle_client_token

  google_client_id="$(resolve_google_client_id)"
  billing_provider="$(resolve_crosswordapi_value "CROSSWORDAPI_BILLING_PROVIDER")"
  paddle_environment="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_ENVIRONMENT")"
  paddle_client_token="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_CLIENT_TOKEN")"
  render_runtime_auth_config "$google_client_id" "$billing_provider" "$paddle_environment" "$paddle_client_token"
}

main "$@"
