#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

readonly runtime_config_path="js/runtime-auth-config.js"

read_env_file_value() {
  local env_file_path="$1"
  local variable_name="$2"

  if [ ! -f "$env_file_path" ]; then
    return 0
  fi

  sed -n "s/^${variable_name}=//p" "$env_file_path" | head -n 1 | tr -d '\r'
}

resolve_google_client_id() {
  local resolved_google_client_id="${GOOGLE_CLIENT_ID:-}"

  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.tauth" "GOOGLE_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.crosswordapi" "GOOGLE_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  resolved_google_client_id="$(read_env_file_value ".env.tauth" "APP_GOOGLE_WEB_CLIENT_ID")"
  if [ -n "$resolved_google_client_id" ]; then
    printf '%s' "$resolved_google_client_id"
    return 0
  fi

  echo "Missing GOOGLE_CLIENT_ID. Set it in the shell, .env.tauth, or .env.crosswordapi." >&2
  return 1
}

resolve_crosswordapi_value() {
  local variable_name="$1"
  local resolved_value="${!variable_name:-}"

  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  resolved_value="$(read_env_file_value ".env.crosswordapi" "$variable_name")"
  printf '%s' "$resolved_value"
}

resolve_runtime_value() {
  local variable_name="$1"
  local fallback_value="${2:-}"
  local resolved_value="${!variable_name:-}"

  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  printf '%s' "$fallback_value"
}

render_runtime_auth_config() {
  local google_client_id="$1"
  local billing_provider="$2"
  local paddle_environment="$3"
  local paddle_client_token="$4"
  local api_base_url="$5"
  local auth_base_url="$6"
  local config_url="$7"
  local tauth_script_url="$8"
  local billing_enabled="false"

  if [ "$billing_provider" = "paddle" ] && [ -n "$paddle_environment" ] && [ -n "$paddle_client_token" ]; then
    billing_enabled="true"
  fi

  cat > "$runtime_config_path" <<EOF
// Generated by scripts/render-runtime-auth-config.sh.
// The committed copy provides Pages-safe defaults and local runs may overwrite it.
(function initRuntimeAuthConfig(globalScope) {
  "use strict";

  globalScope.LLMCrosswordRuntimeConfig = Object.freeze({
    billing: Object.freeze({
      clientToken: "${paddle_client_token}",
      enabled: ${billing_enabled},
      environment: "${paddle_environment}",
      providerCode: "${billing_provider}",
    }),
    googleClientId: "${google_client_id}",
    services: Object.freeze({
      apiBaseUrl: "${api_base_url}",
      authBaseUrl: "${auth_base_url}",
      configUrl: "${config_url}",
      tauthScriptUrl: "${tauth_script_url}",
    }),
  });
})(window);
EOF
}

main() {
  local google_client_id
  local billing_provider
  local paddle_environment
  local paddle_client_token
  local site_origin
  local api_base_url
  local auth_base_url
  local config_url
  local tauth_script_url

  google_client_id="$(resolve_google_client_id)"
  billing_provider="$(resolve_crosswordapi_value "CROSSWORDAPI_BILLING_PROVIDER")"
  paddle_environment="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_ENVIRONMENT")"
  paddle_client_token="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_CLIENT_TOKEN")"
  site_origin="$(resolve_runtime_value "SITE_ORIGIN" "")"
  api_base_url="$(resolve_runtime_value "LLM_CROSSWORD_API_BASE_URL" "$site_origin")"
  auth_base_url="$(resolve_runtime_value "LLM_CROSSWORD_AUTH_BASE_URL" "$site_origin")"
  config_url="$(resolve_runtime_value "LLM_CROSSWORD_CONFIG_URL" "${api_base_url%/}/config.yml")"
  tauth_script_url="$(resolve_runtime_value "LLM_CROSSWORD_TAUTH_SCRIPT_URL" "${auth_base_url%/}/tauth.js")"
  render_runtime_auth_config \
    "$google_client_id" \
    "$billing_provider" \
    "$paddle_environment" \
    "$paddle_client_token" \
    "$api_base_url" \
    "$auth_base_url" \
    "$config_url" \
    "$tauth_script_url"
}

main "$@"
